from dash import html
import dash_bootstrap_components as dbc
from dash.development.base_component import Component as DashComponent

from ..base import BaseComponent

import logging
logger = logging.getLogger(__name__)

class DetailsPanel(BaseComponent):
    """Main details panel container.

    Note: The actual content is generated by the details callback using
    the individual viewer components (DetailsStatsViewer, DetailsImageViewer, etc.).
    This class only provides the panel structure/layout.
    """

    def __init__(self, id_prefix: str = 'details'):
        super().__init__(id_prefix=id_prefix)

    def register_callbacks(self, app):
        """Register callbacks for the panel."""
        pass

    @property
    def content(self) -> list:
        """Return placeholder content.

        Note: In practice, the content is dynamically generated by the
        details callback and injected into the 'details-content' div.
        """
        return []

    @property # Can probably turn this whole thing just into some skeleton
    def _header(self) -> DashComponent:
        return dbc.CardHeader([
            html.Div([
                html.Span("Location Detail", className='fw-bold'),
                dbc.Button(
                    html.I(className='fas fa-chevron-down'),
                    id='details-collapse-btn',
                    color='link', size='sm', className='ms-auto p-0'
                )
            ], className='d-flex align-items-center justify-content-between')
        ])
        
    @property
    def _body(self) -> DashComponent:
        return dbc.Collapse([
            dbc.CardBody(
                self.content,
                id='details-content',
                style={'maxHeight': '100%', 'overflowY': 'auto'}
            )
        ], id='details-collapse', is_open=True)
    
    @property
    def layout(self) -> DashComponent:
        """Return the complete panel with card wrapper (for use in layout)."""
        # Return complete card structure with floating style
        # Note: Card visibility is controlled by the details callback via 'details-card' style
        return html.Div([
            dbc.Card([
                self._header,
                self._body
            ], id='details-card', style={'display': 'none'})
        ], style={ # TODO: !! Move to an actual style file
            'position': 'absolute',
            'top': '10px',
            'left': '10px',
            'width': '25%',
            'maxHeight': 'calc(80vh - 20px)',
            'overflowY': 'auto',
            'zIndex': 1000
        })

